apiVersion: v1
kind: Service
metadata:
  name: gol
  labels: 
    app: golsvc
spec:
  type: LoadBalancer
  selector:
    app: golsvc
  ports:
    - name: spcport
      port: 32500
      targetPort: 8080
