apiVersion: v1
kind: Service
metadata:
  name: spc
  labels: 
    app: spcsvc
spec:
  type: LoadBalancer
  selector:
    app: spcsvc
  ports:
    - name: spcport
      port: 32500
      targetPort: 8080
